apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.17.5
  http:
    service:
      spec:
        type: LoadBalancer  
  nodeSets:
  - name: default
    count: 3
    config:
      node.roles: [ "master", "data", "ingest" ]
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
    podTemplate:
      metadata:
        labels:
          foo: bar
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          resources:
            requests:
              memory: 1.5Gi
              cpu: 0.2
            limits:
              memory: 2Gi
              cpu: 1
#          readinessProbe:
#            httpGet:
#              scheme: HTTPS
#              port: 9200
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-quickstart
spec:
  version: 7.17.5
  http:
    service:
      spec:
        type: LoadBalancer  
  count: 1
  elasticsearchRef:
    name: quickstart
#  config:
#    server:
#      rewriteBasePath: true
#      basePath: "/kibana"
#      publicBaseUrl: "https://kb-quickstart/kibana"
#  podTemplate:
#    spec:
#      containers:
#        - name: kibana
#          readinessProbe:
#            httpGet:
#              scheme: HTTPS
#              path: "/kibana/login"
#              port: 5601
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 7.17.5
  count: 1
  elasticsearchRef:
    name: quickstart
